# Generated by Django 4.2.6 on 2023-10-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500)),
                (
                    "time_scraped",
                    models.DateTimeField(auto_now=True, verbose_name="Date scraped"),
                ),
                ("price", models.FloatField()),
                ("description", models.CharField(max_length=500)),
                ("attributes", models.JSONField()),
                ("category", models.JSONField()),
                ("is_available", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500)),
                (
                    "time_scraped",
                    models.DateTimeField(auto_now=True, verbose_name="Date scraped"),
                ),
                ("is_new", models.BooleanField()),
            ],
        ),
    ]
