# Generated by Django 4.2.6 on 2023-10-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='thing', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
